export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/coATv42PoiLqAFKStJiMZs2r6Zb.jpg',
      genre_ids: [16, 10751, 18, 12, 35],
      id: 1022789,
      original_language: 'en',
      original_title: 'Inside Out 2',
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 9750.804,
      poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
      release_date: '2024-06-11',
      title: 'Inside Out 2',
      video: false,
      vote_average: 7.756,
      vote_count: 211,
    },
    {
      adult: false,
      backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: 'en',
      original_title: 'Kingdom of the Planet of the Apes',
      overview:
        "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
      popularity: 4014.879,
      poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
      release_date: '2024-05-08',
      title: 'Kingdom of the Planet of the Apes',
      video: false,
      vote_average: 6.827,
      vote_count: 1075,
    },
    {
      adult: false,
      backdrop_path: '/hliXekHv7xc2cgXnMBLlp4Eihq8.jpg',
      genre_ids: [53, 27, 28, 9648],
      id: 1001311,
      original_language: 'fr',
      original_title: 'Sous la Seine',
      overview:
        'In the Summer of 2024, Paris is hosting the World Triathlon Championships on the Seine for the first time. Sophia, a brilliant scientist, learns from Mika, a young environmental activist, that a large shark is swimming deep in the river. To avoid a bloodbath at the heart of the city, they have no choice but to join forces with Adil, the Seine river police commander.',
      popularity: 2822.686,
      poster_path: '/qZPLK5ktRKa3CL4sKRZtj8UlPYc.jpg',
      release_date: '2024-06-05',
      title: 'Under Paris',
      video: false,
      vote_average: 5.819,
      vote_count: 526,
    },
    {
      adult: false,
      backdrop_path: '/gRApXuxWmO2forYTuTmcz5RaNUV.jpg',
      genre_ids: [28, 80, 53, 35],
      id: 573435,
      original_language: 'en',
      original_title: 'Bad Boys: Ride or Die',
      overview:
        'After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.',
      popularity: 2744.583,
      poster_path: '/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg',
      release_date: '2024-06-05',
      title: 'Bad Boys: Ride or Die',
      video: false,
      vote_average: 7.069,
      vote_count: 303,
    },
    {
      adult: false,
      backdrop_path: '/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg',
      genre_ids: [16, 10751, 12, 18, 35],
      id: 150540,
      original_language: 'en',
      original_title: 'Inside Out',
      overview:
        'From an adventurous balloon ride above the clouds to a monster-filled metropolis, Academy Award®-winning director Pete Docter (“Monsters, Inc.,” “Up”) has taken audiences to unique and imaginative places. In Disney and Pixar’s original movie “ Inside Out,” he will take us to the most extraordinary location of all—inside the mind.',
      popularity: 2731.637,
      poster_path: '/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
      release_date: '2015-06-17',
      title: 'Inside Out',
      video: false,
      vote_average: 7.916,
      vote_count: 20590,
    },
    {
      adult: false,
      backdrop_path: '/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg',
      genre_ids: [878, 28, 12],
      id: 823464,
      original_language: 'en',
      original_title: 'Godzilla x Kong: The New Empire',
      overview:
        'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
      popularity: 2007.024,
      poster_path: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
      release_date: '2024-03-27',
      title: 'Godzilla x Kong: The New Empire',
      video: false,
      vote_average: 7.218,
      vote_count: 2796,
    },
    {
      adult: false,
      backdrop_path: '/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg',
      genre_ids: [10752, 28, 18],
      id: 929590,
      original_language: 'en',
      original_title: 'Civil War',
      overview:
        'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
      popularity: 1707.985,
      poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
      release_date: '2024-04-10',
      title: 'Civil War',
      video: false,
      vote_average: 7.008,
      vote_count: 1577,
    },
    {
      adult: false,
      backdrop_path: '/vblTCXOWUQGSc837vgbhDRi4HSc.jpg',
      genre_ids: [28, 80, 35, 53],
      id: 955555,
      original_language: 'ko',
      original_title: '범죄도시3',
      overview:
        'Detective Ma Seok-do changes his affiliation from the Geumcheon Police Station to the Metropolitan Investigation Team, in order to eradicate Japanese gangsters who enter Korea to commit heinous crimes.',
      popularity: 1415.101,
      poster_path: '/lW6IHrtaATxDKYVYoQGU5sh0OVm.jpg',
      release_date: '2023-05-31',
      title: 'The Roundup: No Way Out',
      video: false,
      vote_average: 7.071,
      vote_count: 266,
    },
    {
      adult: false,
      backdrop_path: '/3TNSoa0UHGEzEz5ndXGjJVKo8RJ.jpg',
      genre_ids: [878, 28],
      id: 614933,
      original_language: 'en',
      original_title: 'Atlas',
      overview:
        'A brilliant counterterrorism analyst with a deep distrust of AI discovers it might be her only hope when a mission to capture a renegade robot goes awry.',
      popularity: 1161.652,
      poster_path: '/bcM2Tl5HlsvPBnL8DKP9Ie6vU4r.jpg',
      release_date: '2024-05-23',
      title: 'Atlas',
      video: false,
      vote_average: 6.765,
      vote_count: 790,
    },
    {
      adult: false,
      backdrop_path: '/kZbTOcTrEGyroQMWQSGIRlNSkwP.jpg',
      genre_ids: [878, 28, 14, 12],
      id: 626412,
      original_language: 'ko',
      original_title: '외계+인 2부',
      overview:
        'Ean has a critical mission to return to the future to save everyone. However, she becomes trapped in the distant past while trying to prevent the escape of alien prisoners who are locked up in the bodies of humans. Meanwhile, Muruk, who helps Ean escape various predicaments, is unnerved when he begins sensing the presence of a strange being in his body. Traveling through the centuries, they are trying to prevent the explosion of the haava.',
      popularity: 1113.643,
      poster_path: '/4RClncz0GTKPZzSAcAalHCw0h3g.jpg',
      release_date: '2024-01-10',
      title: 'Alienoid: Return to the Future',
      video: false,
      vote_average: 6.556,
      vote_count: 240,
    },
    {
      adult: false,
      backdrop_path: '/oavbmL3iddJUmC8nQjL6bLHwAP4.jpg',
      genre_ids: [27],
      id: 719221,
      original_language: 'en',
      original_title: 'Tarot',
      overview:
        'When a group of friends recklessly violate the sacred rule of Tarot readings, they unknowingly unleash an unspeakable evil trapped within the cursed cards. One by one, they come face to face with fate and end up in a race against death.',
      popularity: 1099.786,
      poster_path: '/gAEUXC37vl1SnM7PXsHTF23I2vq.jpg',
      release_date: '2024-05-01',
      title: 'Tarot',
      video: false,
      vote_average: 6.479,
      vote_count: 507,
    },
    {
      adult: false,
      backdrop_path: '/oZDRuGHhe5uY8wBqFJcJZT9kdvJ.jpg',
      genre_ids: [27, 9648, 53],
      id: 1086747,
      original_language: 'en',
      original_title: 'The Watchers',
      overview:
        'A young artist gets stranded in an extensive, immaculate forest in western Ireland, where, after finding shelter, she becomes trapped alongside three strangers, stalked by mysterious creatures each night.',
      popularity: 1117.26,
      poster_path: '/vZVEUPychdvZLrTNwWErr9xZFmu.jpg',
      release_date: '2024-06-06',
      title: 'The Watchers',
      video: false,
      vote_average: 5.82,
      vote_count: 128,
    },
    {
      adult: false,
      backdrop_path: '/kYgQzzjNis5jJalYtIHgrom0gOx.jpg',
      genre_ids: [16, 28, 10751, 35, 14],
      id: 1011985,
      original_language: 'en',
      original_title: 'Kung Fu Panda 4',
      overview:
        'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.',
      popularity: 1015.949,
      poster_path: '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
      release_date: '2024-03-02',
      title: 'Kung Fu Panda 4',
      video: false,
      vote_average: 7.111,
      vote_count: 2016,
    },
    {
      adult: false,
      backdrop_path: '/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg',
      genre_ids: [28, 35],
      id: 746036,
      original_language: 'en',
      original_title: 'The Fall Guy',
      overview:
        'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.',
      popularity: 895.517,
      poster_path: '/aBkqu7EddWK7qmY4grL4I6edx2h.jpg',
      release_date: '2024-04-24',
      title: 'The Fall Guy',
      video: false,
      vote_average: 7.25,
      vote_count: 1270,
    },
    {
      adult: false,
      backdrop_path: '/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg',
      genre_ids: [10749, 35, 80],
      id: 974635,
      original_language: 'en',
      original_title: 'Hit Man',
      overview:
        'A mild-mannered professor moonlighting as a fake hit man in police stings ignites a chain reaction of trouble when he falls for a potential client.',
      popularity: 832.05,
      poster_path: '/1126gjlBf4hTm9Sgf0ox3LGVEBt.jpg',
      release_date: '2024-05-16',
      title: 'Hit Man',
      video: false,
      vote_average: 7.039,
      vote_count: 304,
    },
    {
      adult: false,
      backdrop_path: '/9Or1qeUZyOSQVglRXGnqc6owp21.jpg',
      genre_ids: [28],
      id: 1115623,
      original_language: 'en',
      original_title: 'The Last Kumite',
      overview:
        'When Karate champion Michael Rivers wins the last tournament of his career, shady businessman Ron Hall offers him the opportunity to fight in an illegal Kumite in Bulgaria against the world’s best martial artists.  When Michael declines, Hall has his daughter kidnapped and, in order to rescue her, Rivers is left with no choice but to compete in the deadly tournament. Arriving in Bulgaria, he finds out that he is not the only fighter whose loved one was taken. Rivers enlists the help of trainers Master Loren, and Julie Jackson but will it be enough for him to win the tournament and save his daughter’s life?',
      popularity: 1246.18,
      poster_path: '/zDkaJgsPoSqa2cMe2hW2HAfyWwO.jpg',
      release_date: '2024-05-09',
      title: 'The Last Kumite',
      video: false,
      vote_average: 5.429,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: '/eAIHqfS3kXm7kZl4j7ZBfdegyEz.jpg',
      genre_ids: [53, 28, 80],
      id: 38700,
      original_language: 'en',
      original_title: 'Bad Boys for Life',
      overview:
        'Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.',
      popularity: 835.489,
      poster_path: '/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg',
      release_date: '2020-01-15',
      title: 'Bad Boys for Life',
      video: false,
      vote_average: 7.124,
      vote_count: 7905,
    },
    {
      adult: false,
      backdrop_path: '/11G6N5zW0KykVS0EcNKeXHUmQj8.jpg',
      genre_ids: [10752],
      id: 1136318,
      original_language: 'en',
      original_title: 'Battle Over Britain',
      overview:
        'A young pilot, fresh out of training, is called to join a Flight while they wait for the call to scramble. Throughout a single day, he witnesses the skies of southern England filled with deadly dog fights, and after every exhausting battle the men return to their dispersal hut, only to find another of their number missing. Unwilling to surrender, the pilot and his comrades unite to take to the skies once more, determined to defend not only the airfield, but their entire country.',
      popularity: 799.489,
      poster_path: '/8htJ7keZTwa08aC9OKyiqaq1cNJ.jpg',
      release_date: '2023-12-01',
      title: 'Battle Over Britain',
      video: false,
      vote_average: 6.597,
      vote_count: 31,
    },
    {
      adult: false,
      backdrop_path: '/v6c8WeF21R9gzrIIyfcM9y5xzJz.jpg',
      genre_ids: [28, 12, 878],
      id: 786892,
      original_language: 'en',
      original_title: 'Furiosa: A Mad Max Saga',
      overview:
        'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.',
      popularity: 757.234,
      poster_path: '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
      release_date: '2024-05-22',
      title: 'Furiosa: A Mad Max Saga',
      video: false,
      vote_average: 7.621,
      vote_count: 918,
    },
    {
      adult: false,
      backdrop_path: '/iafs5DG5fGq7ef0acl3xlX4BFrs.jpg',
      genre_ids: [18, 10770],
      id: 1219685,
      original_language: 'fr',
      original_title: 'Un père idéal',
      overview: '',
      popularity: 517.23,
      poster_path: '/4xJd3uwtL1vCuZgEfEc8JXI9Uyx.jpg',
      release_date: '2024-04-21',
      title: 'Un père idéal',
      video: false,
      vote_average: 5.894,
      vote_count: 47,
    },
  ],
  total_pages: 44721,
  total_results: 894414,
};

export const genres = [
  { id: 0, name: 'Latest' },
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
];

export const details = {
  adult: false,
  backdrop_path: '/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
  belongs_to_collection: {
    id: 1022790,
    name: 'Inside Out Collection',
    poster_path: '/Apr19lGxP7gm6y2HQX0kqOXTtqC.jpg',
    backdrop_path: '/7U2m2dMSIfHx2gWXKq78Xj1weuH.jpg',
  },
  budget: 200000000,
  genres: [
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 10751,
      name: 'Family',
    },
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 35,
      name: 'Comedy',
    },
  ],
  homepage: 'https://movies.disney.com/inside-out-2',
  id: 1022789,
  imdb_id: 'tt22022452',
  origin_country: ['US'],
  original_language: 'en',
  original_title: 'Inside Out 2',
  overview:
    "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  popularity: 5165.407,
  poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
  production_companies: [
    {
      id: 2,
      logo_path: '/wdrCwmRnLFJhEoH8GSfymY85KHT.png',
      name: 'Walt Disney Pictures',
      origin_country: 'US',
    },
    {
      id: 3,
      logo_path: '/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png',
      name: 'Pixar',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2024-06-11',
  revenue: 1443875604,
  runtime: 97,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'Make room for new emotions.',
  title: 'Inside Out 2',
  video: false,
  vote_average: 7.646,
  vote_count: 2014,
};
